### ISSUE TITLE
SEND_ID_TO_SURVEY creates unique URL for each worker in survey list

### ISSUE THREAD

**Issue by jeff-hughes** [gideongoldin/TurkGate#92]
When SEND_ID_TO_SURVEY is set to TRUE, the worker IDs get added to the survey URL. This means when it gets added to the database, each worker now has a unique URL -- which makes for a long list of survey URLs in the group on the Generate a HIT page. Instead of one survey URL in the group, now there is one URL for each worker.

This should be a fairly simple matter of differentiating in gateway.php between the URL workers get sent to and the URL that gets saved in the database. I would be happy to work on it and submit a pull request if you would prefer. Would love to be able to contribute to the project, my department has really appreciated TurkGate!

**Comment by jeffzemla** [comment]
This sounds like a great idea Jeff. I hadn't even realized that the URLs
were stored this way when this option is enabled. We definitely encourage
you to contribute and send any pull requests that will improve TurkGate.

Please note that the back-end code for this feature recently changed when
we exposed the option to send the worker id to the survey in the UI. If you
pull the latest commit, you'll see this feature is in webTemplate.html
instead of gateway.php. The problem you mention still needs to be fixed,
though-- and if you'd like to implement a fix, that would be great!
